project:
  type: website

execute:
  freeze: auto

resources:
  - CNAME

website:
  title: "GISRUK 2025"
  favicon: "img/favicon/favicon.ico"
  navbar:
    logo: "img/favicon/apple-touch-icon.png"
    left:
      - href: index.qmd
        text: Home
      # - text: "About"
      #   menu:
      #     - href: about.qmd
      #       text: GISRUK
      #     - href: theme.qmd
      #       text: Conference Theme
      - text: "Participation"
        menu:
          - href: cfp/
            text: Call for papers
          - href: osgeo/
            text: GISRUK & OSGeo:UK GoFundGeo Award
          - href: registration/
            text: Registration
      - text: "Programme"
        menu:
          - href: program/
            text: Conference Programme
          - href: keynotes/
            text: Keynote Speakers
          - href: ecrs/
            text: ECR Sessions
      - href: organisation/
        text: Organisation
      - href: venue/
        text: Venue
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/company/gisruk/
  page-footer:
    # center:
    #   - icon: "img/logos/logo_cdrc.webp"
    #     href: https://www.cdrc.ac.uk
    #   - icon: "img/logos/logo_rgs.webp"
    #     href: https://www.rgs.org/
    #   - icon: "img/logos/OSGeoUK2.png"
    #     href: https://www.osgeo.org/
    right:
      - icon: github
        href: https://github.com/ljwolf/gisruk2025/
      - icon: linkedin
        href:  https://www.linkedin.com/company/gisruk/

format:
  html:
    # theme:
    #   light: flatly
    #   dark: darkly
    theme: gisruk.scss
    toc: true
    include-after-body: footer.html
