project:
  type: website
  resources:
    - GISRUK2025_PaperTemplateSubmission.docx
    - GISRUK2025_PaperTemplateSubmission.zip
    - latex.zip


execute:
  freeze: auto

resources:
  - CNAME

website:
  title: "GISRUK 2025"
  favicon: "img/favicon/favicon.ico"
  navbar:
    logo: "img/favicon/apple-touch-icon.png"
    left:
      - href: index.qmd
        text: Home
      - text: "Submitting"
        menu:
          - href: cfp/
            text: Call for papers
          - href: osgeo/
            text: GISRUK & OSGeo:UK GoFundGeo Award
          - href: https://app.oxfordabstracts.com/stages/76668/review
            text: Reviews
          - href: https://app.oxfordabstracts.com/events/74052/committee/decisions/submissions
            text: Acceptances
      - text: "Attending"
        menu:
          - href: https://shop.bris.ac.uk/conferences-and-events/faculty-of-science/geographical-sciences/conferences/the-33rd-annual-gisruk-conference
            text: Registration
          - href: venue/
            text: Venues
          - href: https://meetbristolbathres.bzon.uk/event/33rd-annual-gis-research-uk-conference/ 
            text: Accommodation 
      - text: "Programme"
        menu:
          - href: program/
            text: Conference Programme
          - href: keynotes/
            text: Keynote Speakers
          - href: ecrs/
            text: ECR Sessions
      - href: organisation/
        text: Organisers
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/company/gisruk/
  page-footer:
    # center:
    #   - icon: "img/logos/logo_cdrc.webp"
    #     href: https://www.cdrc.ac.uk
    #   - icon: "img/logos/logo_rgs.webp"
    #     href: https://www.rgs.org/
    #   - icon: "img/logos/OSGeoUK2.png"
    #     href: https://www.osgeo.org/
    right:
      - icon: github
        href: https://github.com/gisruk/gisruk.github.io/
      - icon: linkedin
        href:  https://www.linkedin.com/company/gisruk/

format:
  html:
    # theme:
    #   light: flatly
    #   dark: darkly
    theme: gisruk.scss
    toc: true
    include-after-body: footer.html
