---
title: "GISRUK 2025 : University of Bristol"
---

::: {.callout-important icon=true}


### Updates

**Best paper / poster prize**. As ever, remember to vote for the [{{< fa solid link >}}Best Paper awards](https://forms.gle/XZEFKSbdxwEAbpfg8). 

**Socials**. This evening's conference dinner is at [{{< fa solid link >}}Browns Brasserie](https://www.browns-restaurants.co.uk/restaurants/southwest/bristol#/) from 19:00. Please check your order [{{< fa solid link >}}here](venue/#browns-dinner-orders)

:::


---------

Welcome to the 33rd Annual GIS Research UK Conference. The conference will be hosted at University of Bristol on 23rd – 25th April 2025.

GISRUK attracts international researchers and practitioners from geographic information science and related fields to share and discuss the latest advances in spatial computing and analysis. The work presented at GISRUK covers fundamental research, methodological approaches, and applications of GIScience across many domains.

We welcome papers covering all aspects of GIS, both methodological and applied. This year, we are particularly excited to invite submissions that investigate Process in Geographic Information Science, including innovations in causal inference, graphical modelling, or re-thinking the link between the patterns we see and what we represent on our computer screens.

## Accommodation

The *Bristol and Bath Convention Bureau* has generously provided a local acommodation website with guaranteed rates for conference attendees. To get the conference rate, please book through [the Meet Bristol & Bath Convention Bureau website](https://meetbristolbathres.bzon.uk/event/33rd-annual-gis-research-uk-conference/)

## Key Dates

* Paper submission deadline: ~~9 January 2025~~  31 January 2025
* Paper review notifications: ~~10 February 2025~~ 28 February 2025
* Registration opens: Monday 3 February 2025
* ECR workshops: 22-23 April 2025
* Conference: 23-25 April 2025
