---
title: "Participating in the Conference"
---

# Posters

Posters can be a maximum size of A0 in a landscape format. We will provide the poster stands and pins. 

To help us ensure the posters are up for display by the poster sessions, please bring your poster to the poster hall no later than 10:00 AM on Thursday April 24th. We will have conference staff/volunteers available to assist you in hanging the poster if needed.

# Talks

Talk slots are 20 minutes. We recommend speakers prepare 15 minutes of material, and take questions for five minutes. There are three talks per session. Session information is available on the [Program page](../program). If you are slated to chair a session and cannot attend the conference, please let the local organising team know as soon as possible. 

# Chairing

Session chairs are responsible for keeping the sessions to time. Speakers should present themselves to the chair of the session and come to an agreement about how to present. The rooms come with computers that can be used to show slides, or a speaker/chair can use their laptop for all presentations. However, please minimize the setup/teardown time for speakers by using a single device across the session for all presentations. 

Chairs should ensure talks start at their scheduled times. This means chairs should give each speaker about 15 minutes to speak with 5 minutes left for questions from the audience. To support these timings, chairs should provide speakers with a non-verbal warning when they have spoken for 10 minutes (i.e. 5 minutes remaining), for 13 minutes (i.e. 2 minutes remaining), and 15 minutes (i.e. further speaking will cut into alotted question time). At 19 minutes, the chair must close the Q&A and transition to the next speaker. 

# Voting for awards

Information will be posted at the conference on how to vote for your favorite paper. We will use voting from attendees to determine the **Best Overall Paper** and the **Best Overall Poster**. In addition, the [GoFundGeo](../osgeo) and the [Sinesio Alves Junior](https://www.ucl.ac.uk/bartlett/casa/remembering-sinesio-alves-junior) prizes will be administered by OSGeo:UK and CASA, respectively. 
